
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wcmrvwuzpxojomzddsix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndjbXJ2d3V6cHhvam9temRkc2l4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5OTM1MzUsImV4cCI6MjA2MzU2OTUzNX0.cibdqFeiDhPaPzBJEOUsMPR4nRb07aLFleHHAE8p57c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
